draw_set_font(fn_middle)
draw_set_color(c_dkgray)
draw_set_valign(fa_center)
draw_set_halign(fa_center)
draw_text(x,y,string("Packager : ")+string(package_type)+string("\n")+string(var_status)+string("\n")+string(unsigned_status))